-- 企业微信群机器人填报提醒配置表
-- 在 Supabase SQL Editor 中执行此文件

CREATE TABLE IF NOT EXISTS reminder_configs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  org_id BIGINT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  webhook_url TEXT,
  enabled BOOLEAN DEFAULT FALSE,
  start_time TEXT DEFAULT '12:00',
  end_time TEXT DEFAULT '20:00',
  interval_minutes INTEGER DEFAULT 60 CHECK (interval_minutes >= 15),
  last_reminded_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(org_id)
);

-- ============================================================
-- 操作日志表
-- ============================================================
CREATE TABLE IF NOT EXISTS audit_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID,
  user_name TEXT,
  action TEXT NOT NULL,
  target TEXT,
  detail TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE audit_logs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "管理员可查看日志" ON audit_logs FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM profiles
      WHERE profiles.id = auth.uid()
      AND profiles.role IN ('超级管理员', '管理员')
    )
  );

CREATE POLICY "用户可创建日志" ON audit_logs FOR INSERT
  WITH CHECK (auth.uid() IS NOT NULL);

-- ============================================================
-- 提醒配置表 RLS
-- ============================================================
ALTER TABLE reminder_configs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "管理员可管理提醒配置" ON reminder_configs
  USING (
    EXISTS (
      SELECT 1 FROM profiles
      WHERE profiles.id = auth.uid()
      AND profiles.role IN ('超级管理员', '管理员')
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM profiles
      WHERE profiles.id = auth.uid()
      AND profiles.role IN ('超级管理员', '管理员')
    )
  );
