-- ============================================================
-- 平台模块身份表：支持一套账号多模块身份
-- 在 Supabase SQL Editor 中执行
-- ============================================================

-- 模块身份表：记录一个人在某个模块里的角色和归属组织
CREATE TABLE IF NOT EXISTS module_memberships (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  module_key TEXT NOT NULL,
  role TEXT NOT NULL,
  org_id BIGINT REFERENCES organizations(id) ON DELETE SET NULL,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_module_memberships_unique
ON module_memberships(user_id, module_key, role, COALESCE(org_id, 0));

CREATE INDEX IF NOT EXISTS idx_module_memberships_user
ON module_memberships(user_id, enabled);

CREATE INDEX IF NOT EXISTS idx_module_memberships_module
ON module_memberships(module_key, enabled);

-- ============================================================
-- RLS
-- ============================================================
ALTER TABLE module_memberships ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "管理员可管理模块身份" ON module_memberships;
CREATE POLICY "管理员可管理模块身份" ON module_memberships FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM profiles
      WHERE profiles.id = auth.uid()
      AND profiles.role IN ('超级管理员', '管理员')
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM profiles
      WHERE profiles.id = auth.uid()
      AND profiles.role IN ('超级管理员', '管理员')
    )
  );

DROP POLICY IF EXISTS "用户可查看自己的模块身份" ON module_memberships;
CREATE POLICY "用户可查看自己的模块身份" ON module_memberships FOR SELECT
  USING (user_id = auth.uid());

-- ============================================================
-- 迁移现有 profiles 账号为 supervision 模块身份
-- ============================================================
INSERT INTO module_memberships (user_id, module_key, role, org_id, enabled)
SELECT
  id,
  'supervision',
  role,
  organization_id,
  TRUE
FROM profiles
WHERE role IS NOT NULL
ON CONFLICT (user_id, module_key, role, COALESCE(org_id, 0)) DO NOTHING;
