-- ============================================================
-- 学委模块：岗位摊派与人员落位
-- 在 Supabase SQL Editor 中执行
-- ============================================================

-- 1. 岗位需求 / 摊派表
CREATE TABLE IF NOT EXISTS study_assignment_demands (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  schedule_instance_id BIGINT NOT NULL REFERENCES study_schedule_instances(id) ON DELETE CASCADE,
  from_org_id BIGINT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  target_org_id BIGINT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  target_level TEXT NOT NULL CHECK (target_level IN ('班级', '小组')),
  demand_type TEXT NOT NULL CHECK (demand_type IN ('organizer', 'participant')),
  role_name TEXT NOT NULL,
  required_count INTEGER NOT NULL DEFAULT 1 CHECK (required_count > 0),
  note TEXT,
  created_by UUID REFERENCES profiles(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_study_demands_schedule
ON study_assignment_demands(schedule_instance_id);

CREATE INDEX IF NOT EXISTS idx_study_demands_target
ON study_assignment_demands(target_org_id, target_level);

-- 2. 最终人员落位表
CREATE TABLE IF NOT EXISTS study_assignment_people (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  demand_id BIGINT NOT NULL REFERENCES study_assignment_demands(id) ON DELETE CASCADE,
  person_id BIGINT REFERENCES people(id) ON DELETE SET NULL,
  person_name_snapshot TEXT NOT NULL,
  source_type TEXT NOT NULL DEFAULT 'person' CHECK (source_type IN ('person', 'manual')),
  note TEXT,
  created_by UUID REFERENCES profiles(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_study_people_demand
ON study_assignment_people(demand_id);

-- ============================================================
-- RLS
-- ============================================================
ALTER TABLE study_assignment_demands ENABLE ROW LEVEL SECURITY;
ALTER TABLE study_assignment_people ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "管理员可管理学委摊派" ON study_assignment_demands;
CREATE POLICY "管理员可管理学委摊派" ON study_assignment_demands FOR ALL
  USING (
    EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role IN ('超级管理员', '管理员'))
  )
  WITH CHECK (
    EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role IN ('超级管理员', '管理员'))
  );

DROP POLICY IF EXISTS "认证用户可查看摊派" ON study_assignment_demands;
CREATE POLICY "认证用户可查看摊派" ON study_assignment_demands FOR SELECT
  USING (auth.uid() IS NOT NULL);

DROP POLICY IF EXISTS "管理员可管理学委落位" ON study_assignment_people;
CREATE POLICY "管理员可管理学委落位" ON study_assignment_people FOR ALL
  USING (
    EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role IN ('超级管理员', '管理员'))
  )
  WITH CHECK (
    EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role IN ('超级管理员', '管理员'))
  );

DROP POLICY IF EXISTS "认证用户可查看落位" ON study_assignment_people;
CREATE POLICY "认证用户可查看落位" ON study_assignment_people FOR SELECT
  USING (auth.uid() IS NOT NULL);
