-- ============================================================
-- 学委模块基础表：课程内容库、日程规则、日程实例
-- 在 Supabase SQL Editor 中执行
-- ============================================================

-- 1. 课程内容库：全局维护，可被各学期日程引用
CREATE TABLE IF NOT EXISTS study_course_library (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  chapter_no TEXT,
  chapter_title TEXT NOT NULL DEFAULT '',
  theme TEXT NOT NULL DEFAULT '',
  title TEXT NOT NULL,
  study_content TEXT NOT NULL DEFAULT '',
  thinking_questions TEXT NOT NULL DEFAULT '',
  paper_pages TEXT NOT NULL DEFAULT '',
  ebook_url TEXT NOT NULL DEFAULT '',
  sort_order INTEGER NOT NULL DEFAULT 0,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_by UUID REFERENCES profiles(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_study_course_library_active
ON study_course_library(is_active, sort_order, id);

-- 2. 日程规则：定义周几是什么共读层级
CREATE TABLE IF NOT EXISTS study_schedule_rules (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  semester_id BIGINT NOT NULL REFERENCES semesters(id) ON DELETE CASCADE,
  weekday INTEGER NOT NULL CHECK (weekday BETWEEN 1 AND 7),
  scope_level TEXT NOT NULL CHECK (scope_level IN ('大班', '班级', '小组')),
  title TEXT NOT NULL DEFAULT '',
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_study_schedule_rules_unique
ON study_schedule_rules(semester_id, weekday);

-- 3. 日程实例：按规则生成的具体日程
CREATE TABLE IF NOT EXISTS study_schedule_instances (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  semester_id BIGINT NOT NULL REFERENCES semesters(id) ON DELETE CASCADE,
  schedule_date DATE NOT NULL,
  scope_level TEXT NOT NULL CHECK (scope_level IN ('大班', '班级', '小组')),
  org_id BIGINT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  course_id BIGINT REFERENCES study_course_library(id) ON DELETE SET NULL,
  custom_title TEXT,
  custom_theme TEXT,
  custom_content TEXT,
  custom_question TEXT,
  custom_paper_pages TEXT,
  custom_ebook_url TEXT,
  note TEXT,
  created_by UUID REFERENCES profiles(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_study_schedule_instances_unique
ON study_schedule_instances(semester_id, schedule_date, scope_level, org_id);

CREATE INDEX IF NOT EXISTS idx_study_schedule_instances_date
ON study_schedule_instances(semester_id, schedule_date);

-- ============================================================
-- RLS
-- ============================================================
ALTER TABLE study_course_library ENABLE ROW LEVEL SECURITY;
ALTER TABLE study_schedule_rules ENABLE ROW LEVEL SECURITY;
ALTER TABLE study_schedule_instances ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "管理员可管理学委课程库" ON study_course_library;
CREATE POLICY "管理员可管理学委课程库" ON study_course_library FOR ALL
  USING (
    EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role IN ('超级管理员', '管理员'))
  )
  WITH CHECK (
    EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role IN ('超级管理员', '管理员'))
  );

DROP POLICY IF EXISTS "认证用户可查看课程库" ON study_course_library;
CREATE POLICY "认证用户可查看课程库" ON study_course_library FOR SELECT
  USING (auth.uid() IS NOT NULL);

DROP POLICY IF EXISTS "管理员可管理学委日程规则" ON study_schedule_rules;
CREATE POLICY "管理员可管理学委日程规则" ON study_schedule_rules FOR ALL
  USING (
    EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role IN ('超级管理员', '管理员'))
  )
  WITH CHECK (
    EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role IN ('超级管理员', '管理员'))
  );

DROP POLICY IF EXISTS "认证用户可查看日程规则" ON study_schedule_rules;
CREATE POLICY "认证用户可查看日程规则" ON study_schedule_rules FOR SELECT
  USING (auth.uid() IS NOT NULL);

DROP POLICY IF EXISTS "管理员可管理学委日程实例" ON study_schedule_instances;
CREATE POLICY "管理员可管理学委日程实例" ON study_schedule_instances FOR ALL
  USING (
    EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role IN ('超级管理员', '管理员'))
  )
  WITH CHECK (
    EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role IN ('超级管理员', '管理员'))
  );

DROP POLICY IF EXISTS "认证用户可查看日程实例" ON study_schedule_instances;
CREATE POLICY "认证用户可查看日程实例" ON study_schedule_instances FOR SELECT
  USING (auth.uid() IS NOT NULL);
