-- 企业微信群机器人填报提醒配置表
-- 在 Supabase SQL Editor 中执行此文件

CREATE TABLE IF NOT EXISTS reminder_configs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  org_id BIGINT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  webhook_url TEXT,
  enabled BOOLEAN DEFAULT FALSE,
  start_hour INTEGER DEFAULT 12 CHECK (start_hour >= 0 AND start_hour <= 23),
  end_hour INTEGER DEFAULT 20 CHECK (end_hour >= 0 AND end_hour <= 23),
  interval_minutes INTEGER DEFAULT 60 CHECK (interval_minutes >= 15),
  last_reminded_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(org_id)
);

-- 允许管理员读取和修改
ALTER TABLE reminder_configs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "管理员可管理提醒配置" ON reminder_configs
  USING (
    EXISTS (
      SELECT 1 FROM profiles
      WHERE profiles.id = auth.uid()
      AND profiles.role = '管理员'
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM profiles
      WHERE profiles.id = auth.uid()
      AND profiles.role = '管理员'
    )
  );
