-- ============================================================
-- 考核项目提交截止规则表
-- 用于设置考核项目在指定大班、指定星期的提交截止时间
-- ============================================================

CREATE TABLE IF NOT EXISTS assessment_deadline_configs (
  id                  bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  assessment_type_id  integer NOT NULL REFERENCES assessment_types(id) ON DELETE CASCADE,
  org_id              integer NOT NULL,  -- 大班 ID
  day_of_week         integer NOT NULL CHECK (day_of_week BETWEEN 0 AND 6),  -- 0=周日, 5=周五
  cutoff_time         time NOT NULL DEFAULT '07:30',
  is_enabled          boolean NOT NULL DEFAULT true,
  created_at          timestamptz NOT NULL DEFAULT now(),
  updated_at          timestamptz NOT NULL DEFAULT now(),
  UNIQUE (assessment_type_id, org_id, day_of_week)
);

-- RLS: 所有认证用户可读，管理员可写
ALTER TABLE assessment_deadline_configs ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN DROP POLICY IF EXISTS "认证用户可查看截止规则" ON assessment_deadline_configs; EXCEPTION WHEN undefined_object THEN NULL; END $$;
CREATE POLICY "认证用户可查看截止规则" ON assessment_deadline_configs FOR SELECT
  USING (auth.uid() IS NOT NULL);

DO $$ BEGIN DROP POLICY IF EXISTS "管理员可管理截止规则" ON assessment_deadline_configs; EXCEPTION WHEN undefined_object THEN NULL; END $$;
CREATE POLICY "管理员可管理截止规则" ON assessment_deadline_configs FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM profiles
      WHERE profiles.id = auth.uid()
      AND profiles.role IN ('超级管理员', '管理员')
    )
  );
