-- ============================================================
-- 课程合集表 study_courses + study_course_library 增加 course_id
-- 在 Supabase SQL Editor 中执行
-- ============================================================

-- 1. 创建课程合集表
CREATE TABLE IF NOT EXISTS study_courses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  cover_url TEXT NOT NULL DEFAULT '',
  sort_order INTEGER NOT NULL DEFAULT 0,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_study_courses_active
ON study_courses(is_active, sort_order, id);

-- 2. study_course_library 新增 course_id 外键
ALTER TABLE study_course_library ADD COLUMN IF NOT EXISTS course_id BIGINT REFERENCES study_courses(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_study_course_library_course
ON study_course_library(course_id, sort_order);

-- 3. RLS 策略
ALTER TABLE study_courses ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "管理员可管理学委课程合集" ON study_courses;
CREATE POLICY "管理员可管理学委课程合集" ON study_courses FOR ALL
USING (
  EXISTS (
    SELECT 1 FROM module_memberships m
    WHERE m.user_id = auth.uid() AND m.module_key = 'study' AND m.role IN ('admin', 'manager')
  )
);

DROP POLICY IF EXISTS "认证用户可查看课程合集" ON study_courses;
CREATE POLICY "认证用户可查看课程合集" ON study_courses FOR SELECT
USING (is_active = true OR EXISTS (
  SELECT 1 FROM module_memberships m
  WHERE m.user_id = auth.uid() AND m.module_key = 'study'
));

-- 4. 插入"致良知是一种伟大的力量"课程合集
INSERT INTO study_courses (title, description, sort_order)
VALUES ('致良知是一种伟大的力量', '阳明心学经典读本，48章完整课程', 1);

-- 5. 将现有课程关联到该课程合集
UPDATE study_course_library SET course_id = (SELECT id FROM study_courses ORDER BY id DESC LIMIT 1)
WHERE title = '致良知是一种伟大的力量' AND course_id IS NULL;

-- 6. 存储桶：课程封面图
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES ('study-covers', 'study-covers', true, 5242880, ARRAY['image/png', 'image/jpeg', 'image/webp', 'image/gif'])
ON CONFLICT (id) DO NOTHING;

DROP POLICY IF EXISTS "认证用户可查看课程封面" ON storage.objects;
CREATE POLICY "认证用户可查看课程封面" ON storage.objects
FOR SELECT USING (bucket_id = 'study-covers');

DROP POLICY IF EXISTS "管理员可上传课程封面" ON storage.objects;
CREATE POLICY "管理员可上传课程封面" ON storage.objects
FOR INSERT WITH CHECK (
  bucket_id = 'study-covers' AND
  EXISTS (
    SELECT 1 FROM module_memberships m
    WHERE m.user_id = auth.uid() AND m.module_key = 'study' AND m.role IN ('admin', 'manager')
  )
);

DROP POLICY IF EXISTS "管理员可删除课程封面" ON storage.objects;
CREATE POLICY "管理员可删除课程封面" ON storage.objects
FOR DELETE USING (
  bucket_id = 'study-covers' AND
  EXISTS (
    SELECT 1 FROM module_memberships m
    WHERE m.user_id = auth.uid() AND m.module_key = 'study' AND m.role IN ('admin', 'manager')
  )
);
