-- ============================================================
-- 秘书处基础表：人员档案、学期组织归属、职务
-- 在 Supabase SQL Editor 中执行
-- ============================================================

-- 1. 人员档案表：所有成员（不要求有系统账号）
CREATE TABLE IF NOT EXISTS people (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  phone TEXT,
  gender TEXT,
  source_form_id BIGINT,
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'left', 'suspended')),
  note TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_people_phone ON people(phone) WHERE phone IS NOT NULL;

-- 2. 学期组织归属：某人在某学期属于哪个组织
CREATE TABLE IF NOT EXISTS person_org_assignments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  semester_id BIGINT NOT NULL REFERENCES semesters(id) ON DELETE CASCADE,
  person_id BIGINT NOT NULL REFERENCES people(id) ON DELETE CASCADE,
  org_id BIGINT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  org_level TEXT NOT NULL CHECK (org_level IN ('大班', '班级', '小组')),
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'transferred', 'left')),
  joined_at DATE,
  left_at DATE,
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_person_org_unique
ON person_org_assignments(semester_id, person_id, org_id);

CREATE INDEX IF NOT EXISTS idx_person_org_semester
ON person_org_assignments(semester_id, org_id, status);

CREATE INDEX IF NOT EXISTS idx_person_org_person
ON person_org_assignments(person_id, semester_id);

-- 3. 职务表：记录现实中的职务（学委、督察、班长等）
CREATE TABLE IF NOT EXISTS person_positions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  semester_id BIGINT NOT NULL REFERENCES semesters(id) ON DELETE CASCADE,
  person_id BIGINT NOT NULL REFERENCES people(id) ON DELETE CASCADE,
  org_id BIGINT REFERENCES organizations(id) ON DELETE CASCADE,
  position_name TEXT NOT NULL,
  position_scope TEXT NOT NULL CHECK (position_scope IN ('大班', '班级', '小组')),
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_person_positions_unique
ON person_positions(semester_id, person_id, position_name, COALESCE(org_id, 0));

CREATE INDEX IF NOT EXISTS idx_person_positions_org
ON person_positions(semester_id, org_id, position_name);

-- ============================================================
-- RLS
-- ============================================================
ALTER TABLE people ENABLE ROW LEVEL SECURITY;
ALTER TABLE person_org_assignments ENABLE ROW LEVEL SECURITY;
ALTER TABLE person_positions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "管理员可管理 people" ON people;
CREATE POLICY "管理员可管理 people" ON people FOR ALL
  USING (
    EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role IN ('超级管理员', '管理员'))
  )
  WITH CHECK (
    EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role IN ('超级管理员', '管理员'))
  );

DROP POLICY IF EXISTS "认证用户可查看 people" ON people;
CREATE POLICY "认证用户可查看 people" ON people FOR SELECT
  USING (auth.uid() IS NOT NULL);

DROP POLICY IF EXISTS "管理员可管理 person_org_assignments" ON person_org_assignments;
CREATE POLICY "管理员可管理 person_org_assignments" ON person_org_assignments FOR ALL
  USING (
    EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role IN ('超级管理员', '管理员'))
  )
  WITH CHECK (
    EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role IN ('超级管理员', '管理员'))
  );

DROP POLICY IF EXISTS "认证用户可查看 person_org_assignments" ON person_org_assignments;
CREATE POLICY "认证用户可查看 person_org_assignments" ON person_org_assignments FOR SELECT
  USING (auth.uid() IS NOT NULL);

DROP POLICY IF EXISTS "管理员可管理 person_positions" ON person_positions;
CREATE POLICY "管理员可管理 person_positions" ON person_positions FOR ALL
  USING (
    EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role IN ('超级管理员', '管理员'))
  )
  WITH CHECK (
    EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role IN ('超级管理员', '管理员'))
  );

DROP POLICY IF EXISTS "认证用户可查看 person_positions" ON person_positions;
CREATE POLICY "认证用户可查看 person_positions" ON person_positions FOR SELECT
  USING (auth.uid() IS NOT NULL);

-- ============================================================
-- 从现有 profiles 同步人员档案（仅首次执行）
-- ============================================================
INSERT INTO people (name, phone)
SELECT name, phone
FROM profiles
WHERE name IS NOT NULL
AND phone IS NOT NULL
ON CONFLICT (phone) WHERE phone IS NOT NULL DO NOTHING;

INSERT INTO people (name, phone)
SELECT name, phone
FROM profiles
WHERE name IS NOT NULL
AND phone IS NULL
  AND name NOT IN (
    SELECT name FROM people WHERE phone IS NULL AND name IS NOT NULL
  );