-- ============================================================
-- 进班表单表：记录学员入学信息
-- 在 Supabase SQL Editor 中执行
-- ============================================================

CREATE TABLE IF NOT EXISTS entry_forms (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  semester_id BIGINT NOT NULL REFERENCES semesters(id) ON DELETE CASCADE,
  person_id BIGINT REFERENCES people(id) ON DELETE SET NULL,
  name TEXT NOT NULL,
  gender TEXT,
  birth_date DATE,
  city TEXT,
  occupation TEXT,
  hobbies_interests JSONB DEFAULT '[]',
  is_new_student BOOLEAN DEFAULT TRUE,
  desired_gains TEXT,
  desired_role TEXT,
  schedule_acknowledged TEXT DEFAULT '已知晓',
  commitment_signature TEXT,
  status TEXT DEFAULT 'active',
  submitted_at TIMESTAMPTZ DEFAULT NOW(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 索引
CREATE INDEX IF NOT EXISTS idx_entry_forms_semester
ON entry_forms(semester_id, status);

CREATE INDEX IF NOT EXISTS idx_entry_forms_name
ON entry_forms(name);

-- RLS
ALTER TABLE entry_forms ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "管理员可管理进班表单" ON entry_forms;
CREATE POLICY "管理员可管理进班表单" ON entry_forms FOR ALL
  USING (
    EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role IN ('超级管理员', '管理员'))
  )
  WITH CHECK (
    EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role IN ('超级管理员', '管理员'))
  );

DROP POLICY IF EXISTS "秘书处可管理进班表单" ON entry_forms;
CREATE POLICY "秘书处可管理进班表单" ON entry_forms FOR ALL
  USING (
    EXISTS (SELECT 1 FROM module_memberships m WHERE m.user_id = auth.uid() AND m.module_key = 'secretariat' AND m.enabled = true)
  )
  WITH CHECK (
    EXISTS (SELECT 1 FROM module_memberships m WHERE m.user_id = auth.uid() AND m.module_key = 'secretariat' AND m.enabled = true)
  );

DROP POLICY IF EXISTS "认证用户可查看进班表单" ON entry_forms;
CREATE POLICY "认证用户可查看进班表单" ON entry_forms FOR SELECT
  USING (auth.uid() IS NOT NULL);

-- updated_at 触发器
CREATE OR REPLACE FUNCTION update_entry_forms_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_entry_forms_updated_at ON entry_forms;
CREATE TRIGGER trg_entry_forms_updated_at
  BEFORE UPDATE ON entry_forms
  FOR EACH ROW
  EXECUTE FUNCTION update_entry_forms_updated_at();
