-- 学期课程表：平台管理员按学期维护，所有组织课程页只读继承。
CREATE TABLE IF NOT EXISTS public.study_semester_course_schedule (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  semester_id BIGINT NOT NULL REFERENCES public.semesters(id) ON DELETE CASCADE,
  schedule_date DATE NOT NULL,
  course_id BIGINT REFERENCES public.study_course_library(id) ON DELETE SET NULL,
  custom_title TEXT,
  custom_theme TEXT,
  custom_content TEXT,
  custom_question TEXT,
  custom_paper_pages TEXT,
  custom_ebook_url TEXT,
  note TEXT,
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_by UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT study_semester_course_schedule_content_check CHECK (
    course_id IS NOT NULL
    OR NULLIF(BTRIM(custom_title), '') IS NOT NULL
    OR NULLIF(BTRIM(custom_content), '') IS NOT NULL
    OR NULLIF(BTRIM(custom_question), '') IS NOT NULL
  )
);

CREATE INDEX IF NOT EXISTS idx_study_semester_course_schedule_date
ON public.study_semester_course_schedule(semester_id, schedule_date, sort_order, id);

DROP TRIGGER IF EXISTS trg_study_semester_course_schedule_updated_at
ON public.study_semester_course_schedule;
CREATE TRIGGER trg_study_semester_course_schedule_updated_at
  BEFORE UPDATE ON public.study_semester_course_schedule
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();

ALTER TABLE public.study_semester_course_schedule ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "登录用户可查看学期课程表" ON public.study_semester_course_schedule;
CREATE POLICY "登录用户可查看学期课程表"
ON public.study_semester_course_schedule FOR SELECT
TO authenticated
USING (TRUE);

DROP POLICY IF EXISTS "平台管理员可新增学期课程表" ON public.study_semester_course_schedule;
CREATE POLICY "平台管理员可新增学期课程表"
ON public.study_semester_course_schedule FOR INSERT
TO authenticated
WITH CHECK (app_private.is_platform_admin());

DROP POLICY IF EXISTS "平台管理员可修改学期课程表" ON public.study_semester_course_schedule;
CREATE POLICY "平台管理员可修改学期课程表"
ON public.study_semester_course_schedule FOR UPDATE
TO authenticated
USING (app_private.is_platform_admin())
WITH CHECK (app_private.is_platform_admin());

DROP POLICY IF EXISTS "平台管理员可删除学期课程表" ON public.study_semester_course_schedule;
CREATE POLICY "平台管理员可删除学期课程表"
ON public.study_semester_course_schedule FOR DELETE
TO authenticated
USING (app_private.is_platform_admin());

GRANT SELECT, INSERT, UPDATE, DELETE
ON public.study_semester_course_schedule TO authenticated, service_role;
GRANT USAGE, SELECT
ON SEQUENCE public.study_semester_course_schedule_id_seq TO authenticated, service_role;

COMMENT ON TABLE public.study_semester_course_schedule IS
  '学期级课程表模板；组织课程页在没有本级或上级课程覆盖时继承。';
