-- 生活委生日关怀与组织委活动报名工作流。

CREATE TABLE IF NOT EXISTS public.life_care_records (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  semester_id BIGINT NOT NULL REFERENCES public.semesters(id) ON DELETE CASCADE,
  entry_form_id BIGINT NOT NULL REFERENCES public.entry_forms(id) ON DELETE CASCADE,
  org_id BIGINT NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  care_date DATE NOT NULL,
  message TEXT NOT NULL CHECK (LENGTH(BTRIM(message)) BETWEEN 1 AND 1000),
  status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'sent')),
  cared_by UUID NOT NULL REFERENCES public.profiles(id) ON DELETE RESTRICT,
  sent_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (entry_form_id, care_date)
);

CREATE INDEX IF NOT EXISTS idx_life_care_records_scope
ON public.life_care_records(semester_id, org_id, care_date);

CREATE INDEX IF NOT EXISTS idx_life_care_records_cared_by
ON public.life_care_records(cared_by);

CREATE TABLE IF NOT EXISTS public.organization_activities (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  semester_id BIGINT NOT NULL REFERENCES public.semesters(id) ON DELETE CASCADE,
  org_id BIGINT NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  title TEXT NOT NULL CHECK (LENGTH(BTRIM(title)) BETWEEN 2 AND 80),
  description TEXT NOT NULL DEFAULT '' CHECK (LENGTH(description) <= 2000),
  location TEXT NOT NULL CHECK (LENGTH(BTRIM(location)) BETWEEN 1 AND 120),
  starts_at TIMESTAMPTZ NOT NULL,
  ends_at TIMESTAMPTZ,
  registration_deadline TIMESTAMPTZ NOT NULL,
  capacity INTEGER NOT NULL DEFAULT 30 CHECK (capacity BETWEEN 1 AND 2000),
  registered_count INTEGER NOT NULL DEFAULT 0 CHECK (registered_count >= 0),
  status TEXT NOT NULL DEFAULT 'draft'
    CHECK (status IN ('draft', 'open', 'closed', 'completed', 'cancelled')),
  created_by UUID NOT NULL REFERENCES public.profiles(id) ON DELETE RESTRICT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CHECK (ends_at IS NULL OR ends_at > starts_at),
  CHECK (registration_deadline <= starts_at)
);

CREATE INDEX IF NOT EXISTS idx_organization_activities_scope
ON public.organization_activities(semester_id, org_id, status, starts_at);

CREATE INDEX IF NOT EXISTS idx_organization_activities_created_by
ON public.organization_activities(created_by);

CREATE TABLE IF NOT EXISTS public.activity_registrations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  activity_id BIGINT NOT NULL REFERENCES public.organization_activities(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  participant_name TEXT NOT NULL CHECK (LENGTH(BTRIM(participant_name)) BETWEEN 1 AND 50),
  phone TEXT NOT NULL DEFAULT '' CHECK (LENGTH(phone) <= 30),
  note TEXT NOT NULL DEFAULT '' CHECK (LENGTH(note) <= 500),
  status TEXT NOT NULL DEFAULT 'registered' CHECK (status IN ('registered', 'cancelled')),
  registered_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (activity_id, user_id)
);

CREATE INDEX IF NOT EXISTS idx_activity_registrations_activity
ON public.activity_registrations(activity_id, status, registered_at);

CREATE INDEX IF NOT EXISTS idx_activity_registrations_user
ON public.activity_registrations(user_id, status);

CREATE OR REPLACE FUNCTION app_private.validate_activity_registration()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  target_activity public.organization_activities%ROWTYPE;
BEGIN
  IF NEW.status <> 'registered' THEN
    NEW.updated_at = NOW();
    RETURN NEW;
  END IF;

  SELECT *
  INTO target_activity
  FROM public.organization_activities
  WHERE id = NEW.activity_id
  FOR UPDATE;

  IF NOT FOUND OR target_activity.status <> 'open' THEN
    RAISE EXCEPTION '该活动当前不可报名';
  END IF;

  IF target_activity.registration_deadline < NOW() THEN
    RAISE EXCEPTION '该活动报名已截止';
  END IF;

  IF target_activity.registered_count >= target_activity.capacity THEN
    IF TG_OP = 'INSERT' THEN
      RAISE EXCEPTION '该活动报名人数已满';
    ELSIF OLD.status <> 'registered' THEN
      RAISE EXCEPTION '该活动报名人数已满';
    END IF;
  END IF;

  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$;

REVOKE ALL ON FUNCTION app_private.validate_activity_registration() FROM PUBLIC;

DROP TRIGGER IF EXISTS trg_validate_activity_registration ON public.activity_registrations;
CREATE TRIGGER trg_validate_activity_registration
BEFORE INSERT OR UPDATE ON public.activity_registrations
FOR EACH ROW EXECUTE FUNCTION app_private.validate_activity_registration();

CREATE OR REPLACE FUNCTION app_private.sync_activity_registration_count()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  target_activity_id BIGINT;
BEGIN
  target_activity_id = COALESCE(NEW.activity_id, OLD.activity_id);
  UPDATE public.organization_activities activity
  SET registered_count = (
        SELECT COUNT(*)
        FROM public.activity_registrations registration
        WHERE registration.activity_id = target_activity_id
          AND registration.status = 'registered'
      ),
      updated_at = NOW()
  WHERE activity.id = target_activity_id;
  RETURN COALESCE(NEW, OLD);
END;
$$;

REVOKE ALL ON FUNCTION app_private.sync_activity_registration_count() FROM PUBLIC;

DROP TRIGGER IF EXISTS trg_sync_activity_registration_count ON public.activity_registrations;
CREATE TRIGGER trg_sync_activity_registration_count
AFTER INSERT OR UPDATE OR DELETE ON public.activity_registrations
FOR EACH ROW EXECUTE FUNCTION app_private.sync_activity_registration_count();

ALTER TABLE public.life_care_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.organization_activities ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.activity_registrations ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "生活委可查看关怀记录" ON public.life_care_records;
CREATE POLICY "生活委可查看关怀记录"
ON public.life_care_records FOR SELECT TO authenticated
USING (
  app_private.has_module_org_scope(semester_id, 'life', org_id, NULL)
);

DROP POLICY IF EXISTS "生活委可新增关怀记录" ON public.life_care_records;
CREATE POLICY "生活委可新增关怀记录"
ON public.life_care_records FOR INSERT TO authenticated
WITH CHECK (
  app_private.has_module_org_scope(semester_id, 'life', org_id, NULL)
  AND cared_by = (SELECT auth.uid())
);

DROP POLICY IF EXISTS "生活委可修改关怀记录" ON public.life_care_records;
CREATE POLICY "生活委可修改关怀记录"
ON public.life_care_records FOR UPDATE TO authenticated
USING (
  app_private.has_module_org_scope(semester_id, 'life', org_id, NULL)
)
WITH CHECK (
  app_private.has_module_org_scope(semester_id, 'life', org_id, NULL)
  AND cared_by = (SELECT auth.uid())
);

DROP POLICY IF EXISTS "生活委可删除关怀记录" ON public.life_care_records;
CREATE POLICY "生活委可删除关怀记录"
ON public.life_care_records FOR DELETE TO authenticated
USING (
  app_private.has_module_org_scope(semester_id, 'life', org_id, NULL)
);

DROP POLICY IF EXISTS "认证用户可查看开放活动" ON public.organization_activities;
CREATE POLICY "认证用户可查看开放活动"
ON public.organization_activities FOR SELECT TO authenticated
USING (
  status IN ('open', 'closed', 'completed')
  OR app_private.has_module_org_scope(semester_id, 'organization', org_id, NULL)
);

DROP POLICY IF EXISTS "组织委可新增活动" ON public.organization_activities;
CREATE POLICY "组织委可新增活动"
ON public.organization_activities FOR INSERT TO authenticated
WITH CHECK (
  app_private.has_module_org_scope(semester_id, 'organization', org_id, NULL)
  AND created_by = (SELECT auth.uid())
);

DROP POLICY IF EXISTS "组织委可修改活动" ON public.organization_activities;
CREATE POLICY "组织委可修改活动"
ON public.organization_activities FOR UPDATE TO authenticated
USING (
  app_private.has_module_org_scope(semester_id, 'organization', org_id, NULL)
)
WITH CHECK (
  app_private.has_module_org_scope(semester_id, 'organization', org_id, NULL)
);

DROP POLICY IF EXISTS "组织委可删除活动" ON public.organization_activities;
CREATE POLICY "组织委可删除活动"
ON public.organization_activities FOR DELETE TO authenticated
USING (
  app_private.has_module_org_scope(semester_id, 'organization', org_id, NULL)
);

DROP POLICY IF EXISTS "用户和组织委可查看报名" ON public.activity_registrations;
CREATE POLICY "用户和组织委可查看报名"
ON public.activity_registrations FOR SELECT TO authenticated
USING (
  user_id = (SELECT auth.uid())
  OR EXISTS (
    SELECT 1
    FROM public.organization_activities activity
    WHERE activity.id = activity_registrations.activity_id
      AND app_private.has_module_org_scope(
        activity.semester_id, 'organization', activity.org_id, NULL
      )
  )
);

DROP POLICY IF EXISTS "用户可报名开放活动" ON public.activity_registrations;
CREATE POLICY "用户可报名开放活动"
ON public.activity_registrations FOR INSERT TO authenticated
WITH CHECK (
  user_id = (SELECT auth.uid())
  AND EXISTS (
    SELECT 1
    FROM public.organization_activities activity
    WHERE activity.id = activity_registrations.activity_id
      AND activity.status = 'open'
      AND activity.registration_deadline >= NOW()
  )
);

DROP POLICY IF EXISTS "用户可修改自己的报名" ON public.activity_registrations;
CREATE POLICY "用户可修改自己的报名"
ON public.activity_registrations FOR UPDATE TO authenticated
USING (user_id = (SELECT auth.uid()))
WITH CHECK (user_id = (SELECT auth.uid()));

DROP POLICY IF EXISTS "组织委可管理活动报名" ON public.activity_registrations;
CREATE POLICY "组织委可管理活动报名"
ON public.activity_registrations FOR UPDATE TO authenticated
USING (
  EXISTS (
    SELECT 1
    FROM public.organization_activities activity
    WHERE activity.id = activity_registrations.activity_id
      AND app_private.has_module_org_scope(
        activity.semester_id, 'organization', activity.org_id, NULL
      )
  )
)
WITH CHECK (
  EXISTS (
    SELECT 1
    FROM public.organization_activities activity
    WHERE activity.id = activity_registrations.activity_id
      AND app_private.has_module_org_scope(
        activity.semester_id, 'organization', activity.org_id, NULL
      )
  )
);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.life_care_records TO authenticated, service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.organization_activities TO authenticated, service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.activity_registrations TO authenticated, service_role;
GRANT USAGE, SELECT ON SEQUENCE public.life_care_records_id_seq TO authenticated, service_role;
GRANT USAGE, SELECT ON SEQUENCE public.organization_activities_id_seq TO authenticated, service_role;
GRANT USAGE, SELECT ON SEQUENCE public.activity_registrations_id_seq TO authenticated, service_role;

INSERT INTO public.module_memberships (
  user_id, semester_id, module_key, role, org_id, enabled
)
SELECT DISTINCT
  profile.id,
  position.semester_id,
  'life',
  CASE WHEN position.position_name ILIKE '%总生活委%' THEN '总生活委' ELSE '生活委' END,
  position.org_id,
  TRUE
FROM public.person_positions position
JOIN public.people person ON person.id = position.person_id
JOIN public.profiles profile ON profile.phone = person.phone
WHERE position.is_active = TRUE
  AND position.position_name ILIKE '%生活委%'
  AND position.org_id IS NOT NULL
ON CONFLICT DO NOTHING;

INSERT INTO public.module_memberships (
  user_id, semester_id, module_key, role, org_id, enabled
)
SELECT DISTINCT
  profile.id,
  position.semester_id,
  'organization',
  CASE WHEN position.position_name ILIKE '%总组织委%' THEN '总组织委' ELSE '组织委' END,
  position.org_id,
  TRUE
FROM public.person_positions position
JOIN public.people person ON person.id = position.person_id
JOIN public.profiles profile ON profile.phone = person.phone
WHERE position.is_active = TRUE
  AND position.position_name ILIKE '%组织委%'
  AND position.org_id IS NOT NULL
ON CONFLICT DO NOTHING;
