-- ============================================================
-- 学委工作流 v4：可维护共读类型、类型岗位、逐级名额槽位
-- ============================================================

CREATE TABLE IF NOT EXISTS study_reading_types (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  semester_id BIGINT NOT NULL REFERENCES semesters(id) ON DELETE CASCADE,
  org_id BIGINT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  type_name TEXT NOT NULL,
  scope_level TEXT NOT NULL CHECK (scope_level IN ('大班', '班级', '小组')),
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_by UUID REFERENCES profiles(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (semester_id, org_id, type_name)
);

CREATE INDEX IF NOT EXISTS idx_study_reading_types_lookup
ON study_reading_types(semester_id, org_id, is_active, sort_order, id);

CREATE TABLE IF NOT EXISTS study_reading_type_positions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reading_type_id BIGINT NOT NULL REFERENCES study_reading_types(id) ON DELETE CASCADE,
  role_name TEXT NOT NULL,
  required_count INTEGER NOT NULL DEFAULT 1 CHECK (required_count > 0),
  is_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_by UUID REFERENCES profiles(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (reading_type_id, role_name)
);

CREATE INDEX IF NOT EXISTS idx_study_reading_type_positions_lookup
ON study_reading_type_positions(reading_type_id, is_enabled, sort_order, id);

INSERT INTO study_reading_types (semester_id, org_id, type_name, scope_level, sort_order)
SELECT o.semester_id, o.id, seed.type_name, seed.scope_level, seed.sort_order
FROM organizations o
CROSS JOIN (
  VALUES
    ('大班共读', '大班', 10),
    ('班级共读', '班级', 20),
    ('小组共读', '小组', 30)
) AS seed(type_name, scope_level, sort_order)
WHERE o.level = '大班'
ON CONFLICT (semester_id, org_id, type_name) DO NOTHING;

-- 兼容 v3：将每种共读类型原有岗位设置迁移为类型岗位。
INSERT INTO study_reading_type_positions (
  reading_type_id,
  role_name,
  required_count,
  is_enabled,
  sort_order
)
SELECT
  rt.id,
  r.role_name,
  cfg.required_count,
  cfg.is_enabled,
  cfg.sort_order
FROM study_reading_type_roles cfg
JOIN study_roles r ON r.id = cfg.role_id
JOIN study_reading_types rt
  ON rt.semester_id = cfg.semester_id
 AND rt.org_id = cfg.org_id
 AND rt.scope_level = cfg.scope_level
ON CONFLICT (reading_type_id, role_name) DO NOTHING;

ALTER TABLE study_schedule_rules
  ADD COLUMN IF NOT EXISTS reading_type_id BIGINT REFERENCES study_reading_types(id) ON DELETE SET NULL;

ALTER TABLE study_schedule_instances
  ADD COLUMN IF NOT EXISTS reading_type_id BIGINT REFERENCES study_reading_types(id) ON DELETE SET NULL;

ALTER TABLE study_assignment_demands
  ADD COLUMN IF NOT EXISTS type_position_id BIGINT REFERENCES study_reading_type_positions(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS slot_index INTEGER;

CREATE INDEX IF NOT EXISTS idx_study_demands_position_slot
ON study_assignment_demands(type_position_id, slot_index, parent_demand_id);

UPDATE study_schedule_rules rule
SET reading_type_id = rt.id
FROM study_reading_types rt
WHERE rule.reading_type_id IS NULL
  AND rt.semester_id = rule.semester_id
  AND rt.org_id = rule.org_id
  AND rt.scope_level = rule.scope_level;

WITH org_big_class AS (
  SELECT
    o.id AS org_id,
    CASE
      WHEN o.level = '大班' THEN o.id
      WHEN o.level = '班级' THEN o.parent_id
      WHEN o.level = '小组' THEN parent_class.parent_id
    END AS big_class_id
  FROM organizations o
  LEFT JOIN organizations parent_class ON parent_class.id = o.parent_id
)
UPDATE study_schedule_instances instance
SET reading_type_id = rule.reading_type_id
FROM org_big_class map
JOIN study_schedule_rules rule
  ON rule.org_id = map.big_class_id
WHERE instance.reading_type_id IS NULL
  AND map.org_id = instance.org_id
  AND rule.semester_id = instance.semester_id
  AND rule.weekday = EXTRACT(ISODOW FROM instance.schedule_date)::INTEGER
  AND rule.scope_level = instance.scope_level;

ALTER TABLE study_reading_types ENABLE ROW LEVEL SECURITY;
ALTER TABLE study_reading_type_positions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "学委可查看共读类型" ON study_reading_types;
CREATE POLICY "学委可查看共读类型" ON study_reading_types FOR SELECT
  TO authenticated
  USING (
    app_private.has_module_access(
      semester_id, 'study',
      ARRAY['学委', '副学委', '管理员', 'admin', 'manager']
    )
  );

DROP POLICY IF EXISTS "大班学委可管理共读类型" ON study_reading_types;
CREATE POLICY "大班学委可管理共读类型" ON study_reading_types FOR ALL
  TO authenticated
  USING (
    app_private.has_study_membership_at_org(
      semester_id, org_id,
      ARRAY['学委', '副学委', '管理员', 'admin', 'manager']
    )
  )
  WITH CHECK (
    app_private.has_study_membership_at_org(
      semester_id, org_id,
      ARRAY['学委', '副学委', '管理员', 'admin', 'manager']
    )
  );

DROP POLICY IF EXISTS "学委可查看类型岗位" ON study_reading_type_positions;
CREATE POLICY "学委可查看类型岗位" ON study_reading_type_positions FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1
      FROM study_reading_types rt
      WHERE rt.id = study_reading_type_positions.reading_type_id
        AND app_private.has_module_access(
          rt.semester_id, 'study',
          ARRAY['学委', '副学委', '管理员', 'admin', 'manager']
        )
    )
  );

DROP POLICY IF EXISTS "大班学委可管理类型岗位" ON study_reading_type_positions;
CREATE POLICY "大班学委可管理类型岗位" ON study_reading_type_positions FOR ALL
  TO authenticated
  USING (
    EXISTS (
      SELECT 1
      FROM study_reading_types rt
      WHERE rt.id = study_reading_type_positions.reading_type_id
        AND app_private.has_study_membership_at_org(
          rt.semester_id, rt.org_id,
          ARRAY['学委', '副学委', '管理员', 'admin', 'manager']
        )
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1
      FROM study_reading_types rt
      WHERE rt.id = study_reading_type_positions.reading_type_id
        AND app_private.has_study_membership_at_org(
          rt.semester_id, rt.org_id,
          ARRAY['学委', '副学委', '管理员', 'admin', 'manager']
        )
    )
  );

GRANT SELECT, INSERT, UPDATE, DELETE ON study_reading_types TO authenticated, service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON study_reading_type_positions TO authenticated, service_role;
GRANT USAGE, SELECT ON SEQUENCE study_reading_types_id_seq TO authenticated, service_role;
GRANT USAGE, SELECT ON SEQUENCE study_reading_type_positions_id_seq TO authenticated, service_role;
