-- ============================================================
-- 优秀作业与宣委制卡工作流
-- ============================================================

CREATE OR REPLACE FUNCTION app_private.has_module_org_scope(
  target_semester_id BIGINT,
  target_module_key TEXT,
  target_org_id BIGINT,
  allowed_roles TEXT[] DEFAULT NULL
)
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  WITH RECURSIVE target_chain AS (
    SELECT o.id, o.parent_id
    FROM organizations o
    WHERE o.id = target_org_id
      AND o.semester_id = target_semester_id

    UNION ALL

    SELECT parent.id, parent.parent_id
    FROM organizations parent
    JOIN target_chain child ON child.parent_id = parent.id
    WHERE parent.semester_id = target_semester_id
  )
  SELECT app_private.is_platform_admin()
    OR EXISTS (
      SELECT 1
      FROM module_memberships membership
      WHERE membership.user_id = auth.uid()
        AND membership.semester_id = target_semester_id
        AND membership.module_key = target_module_key
        AND membership.enabled = TRUE
        AND (allowed_roles IS NULL OR membership.role = ANY(allowed_roles))
        AND (
          membership.org_id IN (SELECT id FROM target_chain)
          OR (
            membership.org_id IS NULL
            AND membership.role IN ('管理员', 'admin', 'manager')
          )
        )
    );
$$;

REVOKE ALL ON FUNCTION app_private.has_module_org_scope(BIGINT, TEXT, BIGINT, TEXT[]) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION app_private.has_module_org_scope(BIGINT, TEXT, BIGINT, TEXT[]) TO authenticated;

CREATE TABLE IF NOT EXISTS excellent_homework_entries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  semester_id BIGINT NOT NULL REFERENCES semesters(id) ON DELETE CASCADE,
  schedule_id BIGINT NOT NULL REFERENCES schedules(id) ON DELETE CASCADE,
  org_id BIGINT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  slot_index SMALLINT NOT NULL CHECK (slot_index BETWEEN 1 AND 3),
  person_id BIGINT REFERENCES people(id) ON DELETE SET NULL,
  person_name_snapshot TEXT NOT NULL,
  content TEXT NOT NULL CHECK (LENGTH(BTRIM(content)) BETWEEN 1 AND 4000),
  submitted_by UUID REFERENCES profiles(id) ON DELETE SET NULL,
  submitted_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (schedule_id, org_id, slot_index)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_excellent_homework_person_per_day
ON excellent_homework_entries(schedule_id, org_id, person_id)
WHERE person_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_excellent_homework_scope
ON excellent_homework_entries(semester_id, schedule_id, org_id, slot_index);

CREATE OR REPLACE FUNCTION app_private.validate_excellent_homework_entry()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path = public
AS $$
DECLARE
  schedule_semester_id BIGINT;
  schedule_daban_id BIGINT;
  schedule_item_ids TEXT;
  member_name TEXT;
  group_is_in_daban BOOLEAN;
  has_homework_assessment BOOLEAN;
BEGIN
  SELECT s.semester_id, s.org_id, s.item_ids
  INTO schedule_semester_id, schedule_daban_id, schedule_item_ids
  FROM schedules s
  WHERE s.id = NEW.schedule_id
    AND s.is_valid = 1;

  IF NOT FOUND OR schedule_semester_id IS DISTINCT FROM NEW.semester_id THEN
    RAISE EXCEPTION '优秀作业必须关联当前学期的有效督察日程';
  END IF;

  SELECT EXISTS (
    SELECT 1
    FROM assessment_types assessment
    WHERE assessment.semester_id = NEW.semester_id
      AND assessment.type_name ILIKE '%作业%'
      AND POSITION(
        ',' || assessment.id::TEXT || ','
        IN ',' || COALESCE(schedule_item_ids, '') || ','
      ) > 0
  )
  INTO has_homework_assessment;

  IF NOT has_homework_assessment THEN
    RAISE EXCEPTION '该督察日程未配置作业考核填报';
  END IF;

  WITH RECURSIVE org_chain AS (
    SELECT org.id, org.parent_id, org.level
    FROM organizations org
    WHERE org.id = NEW.org_id
      AND org.semester_id = NEW.semester_id
      AND org.level = '小组'

    UNION ALL

    SELECT parent.id, parent.parent_id, parent.level
    FROM organizations parent
    JOIN org_chain child ON child.parent_id = parent.id
    WHERE parent.semester_id = NEW.semester_id
  )
  SELECT EXISTS (
    SELECT 1
    FROM org_chain
    WHERE id = schedule_daban_id
      AND level = '大班'
  )
  INTO group_is_in_daban;

  IF NOT group_is_in_daban THEN
    RAISE EXCEPTION '所选小组不属于该督察日程的大班';
  END IF;

  IF NEW.person_id IS NULL THEN
    RAISE EXCEPTION '请选择优秀作业成员';
  END IF;

  SELECT person.name
  INTO member_name
  FROM people person
  JOIN person_org_assignments assignment
    ON assignment.person_id = person.id
   AND assignment.semester_id = NEW.semester_id
   AND assignment.org_id = NEW.org_id
   AND assignment.org_level = '小组'
   AND assignment.status = 'active'
  WHERE person.id = NEW.person_id
    AND person.status = 'active';

  IF member_name IS NULL THEN
    RAISE EXCEPTION '所选人员不是该小组的在读成员';
  END IF;

  NEW.person_name_snapshot = member_name;
  NEW.content = BTRIM(NEW.content);
  NEW.updated_at = NOW();
  IF TG_OP = 'INSERT' THEN
    NEW.submitted_at = NOW();
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_validate_excellent_homework_entry ON excellent_homework_entries;
CREATE TRIGGER trg_validate_excellent_homework_entry
BEFORE INSERT OR UPDATE ON excellent_homework_entries
FOR EACH ROW EXECUTE FUNCTION app_private.validate_excellent_homework_entry();

CREATE TABLE IF NOT EXISTS publicity_homework_cards (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  semester_id BIGINT NOT NULL REFERENCES semesters(id) ON DELETE CASCADE,
  schedule_id BIGINT NOT NULL REFERENCES schedules(id) ON DELETE CASCADE,
  org_id BIGINT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  title TEXT NOT NULL DEFAULT '今日优秀作业',
  subtitle TEXT NOT NULL DEFAULT '',
  intro_text TEXT NOT NULL DEFAULT '',
  closing_text TEXT NOT NULL DEFAULT '',
  theme TEXT NOT NULL DEFAULT 'vermillion'
    CHECK (theme IN ('vermillion', 'ink', 'jade', 'paper')),
  layout TEXT NOT NULL DEFAULT 'collection'
    CHECK (layout IN ('single', 'collection')),
  status TEXT NOT NULL DEFAULT 'draft'
    CHECK (status IN ('draft', 'ready', 'published')),
  created_by UUID REFERENCES profiles(id) ON DELETE SET NULL,
  updated_by UUID REFERENCES profiles(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (schedule_id, org_id)
);

CREATE INDEX IF NOT EXISTS idx_publicity_cards_scope
ON publicity_homework_cards(semester_id, org_id, schedule_id, status);

CREATE TABLE IF NOT EXISTS publicity_homework_card_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  card_id BIGINT NOT NULL REFERENCES publicity_homework_cards(id) ON DELETE CASCADE,
  entry_id BIGINT NOT NULL REFERENCES excellent_homework_entries(id) ON DELETE RESTRICT,
  sort_order SMALLINT NOT NULL DEFAULT 1 CHECK (sort_order BETWEEN 1 AND 3),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (card_id, entry_id),
  UNIQUE (card_id, sort_order)
);

CREATE INDEX IF NOT EXISTS idx_publicity_card_items_entry
ON publicity_homework_card_items(entry_id);

ALTER TABLE excellent_homework_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE publicity_homework_cards ENABLE ROW LEVEL SECURITY;
ALTER TABLE publicity_homework_card_items ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "学委和宣委可查看优秀作业" ON excellent_homework_entries;
CREATE POLICY "学委和宣委可查看优秀作业"
ON excellent_homework_entries FOR SELECT
TO authenticated
USING (
  app_private.has_module_org_scope(semester_id, 'study', org_id, NULL)
  OR app_private.has_module_org_scope(semester_id, 'publicity', org_id, NULL)
);

DROP POLICY IF EXISTS "学委可填报优秀作业" ON excellent_homework_entries;
CREATE POLICY "学委可填报优秀作业"
ON excellent_homework_entries FOR INSERT
TO authenticated
WITH CHECK (
  app_private.has_module_org_scope(semester_id, 'study', org_id, NULL)
  AND submitted_by = auth.uid()
);

DROP POLICY IF EXISTS "学委可修改优秀作业" ON excellent_homework_entries;
CREATE POLICY "学委可修改优秀作业"
ON excellent_homework_entries FOR UPDATE
TO authenticated
USING (
  app_private.has_module_org_scope(semester_id, 'study', org_id, NULL)
)
WITH CHECK (
  app_private.has_module_org_scope(semester_id, 'study', org_id, NULL)
  AND submitted_by = auth.uid()
);

DROP POLICY IF EXISTS "学委可删除优秀作业" ON excellent_homework_entries;
CREATE POLICY "学委可删除优秀作业"
ON excellent_homework_entries FOR DELETE
TO authenticated
USING (
  app_private.has_module_org_scope(semester_id, 'study', org_id, NULL)
);

DROP POLICY IF EXISTS "宣委可查看宣发卡片" ON publicity_homework_cards;
CREATE POLICY "宣委可查看宣发卡片"
ON publicity_homework_cards FOR SELECT
TO authenticated
USING (
  app_private.has_module_org_scope(semester_id, 'publicity', org_id, NULL)
);

DROP POLICY IF EXISTS "宣委可创建宣发卡片" ON publicity_homework_cards;
CREATE POLICY "宣委可创建宣发卡片"
ON publicity_homework_cards FOR INSERT
TO authenticated
WITH CHECK (
  app_private.has_module_org_scope(semester_id, 'publicity', org_id, NULL)
  AND created_by = auth.uid()
  AND updated_by = auth.uid()
);

DROP POLICY IF EXISTS "宣委可修改宣发卡片" ON publicity_homework_cards;
CREATE POLICY "宣委可修改宣发卡片"
ON publicity_homework_cards FOR UPDATE
TO authenticated
USING (
  app_private.has_module_org_scope(semester_id, 'publicity', org_id, NULL)
)
WITH CHECK (
  app_private.has_module_org_scope(semester_id, 'publicity', org_id, NULL)
  AND updated_by = auth.uid()
);

DROP POLICY IF EXISTS "宣委可删除宣发卡片" ON publicity_homework_cards;
CREATE POLICY "宣委可删除宣发卡片"
ON publicity_homework_cards FOR DELETE
TO authenticated
USING (
  app_private.has_module_org_scope(semester_id, 'publicity', org_id, NULL)
);

DROP POLICY IF EXISTS "宣委可查看宣发选稿" ON publicity_homework_card_items;
CREATE POLICY "宣委可查看宣发选稿"
ON publicity_homework_card_items FOR SELECT
TO authenticated
USING (
  EXISTS (
    SELECT 1
    FROM publicity_homework_cards card
    WHERE card.id = publicity_homework_card_items.card_id
      AND app_private.has_module_org_scope(
        card.semester_id, 'publicity', card.org_id, NULL
      )
  )
);

DROP POLICY IF EXISTS "宣委可管理宣发选稿" ON publicity_homework_card_items;
CREATE POLICY "宣委可管理宣发选稿"
ON publicity_homework_card_items FOR ALL
TO authenticated
USING (
  EXISTS (
    SELECT 1
    FROM publicity_homework_cards card
    WHERE card.id = publicity_homework_card_items.card_id
      AND app_private.has_module_org_scope(
        card.semester_id, 'publicity', card.org_id, NULL
      )
  )
)
WITH CHECK (
  EXISTS (
    SELECT 1
    FROM publicity_homework_cards card
    WHERE card.id = publicity_homework_card_items.card_id
      AND app_private.has_module_org_scope(
        card.semester_id, 'publicity', card.org_id, NULL
      )
  )
);

GRANT SELECT, INSERT, UPDATE, DELETE ON excellent_homework_entries TO authenticated, service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON publicity_homework_cards TO authenticated, service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON publicity_homework_card_items TO authenticated, service_role;
GRANT USAGE, SELECT ON SEQUENCE excellent_homework_entries_id_seq TO authenticated, service_role;
GRANT USAGE, SELECT ON SEQUENCE publicity_homework_cards_id_seq TO authenticated, service_role;
GRANT USAGE, SELECT ON SEQUENCE publicity_homework_card_items_id_seq TO authenticated, service_role;

-- 已有宣委职务且已创建登录账号的人员，启用对应组织范围的宣委模块权限。
INSERT INTO module_memberships (
  user_id,
  semester_id,
  module_key,
  role,
  org_id,
  enabled
)
SELECT DISTINCT
  profile.id,
  position.semester_id,
  'publicity',
  position.position_name,
  position.org_id,
  TRUE
FROM person_positions position
JOIN people person ON person.id = position.person_id
JOIN profiles profile ON profile.phone = person.phone
WHERE position.is_active = TRUE
  AND position.position_name ILIKE '%宣委%'
  AND position.org_id IS NOT NULL
ON CONFLICT DO NOTHING;
