-- ============================================================
-- 每日共读影像：学委提交原图、宣委非破坏裁切与长图制作
-- ============================================================

CREATE TABLE IF NOT EXISTS study_reading_media_assets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  semester_id BIGINT NOT NULL REFERENCES semesters(id) ON DELETE CASCADE,
  schedule_instance_id BIGINT NOT NULL REFERENCES study_schedule_instances(id) ON DELETE CASCADE,
  org_id BIGINT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  asset_kind TEXT NOT NULL DEFAULT 'other'
    CHECK (asset_kind IN ('role', 'overview', 'moment', 'other')),
  demand_id BIGINT REFERENCES study_assignment_demands(id) ON DELETE SET NULL,
  assignment_person_id BIGINT REFERENCES study_assignment_people(id) ON DELETE SET NULL,
  role_name_snapshot TEXT NOT NULL DEFAULT '',
  person_name_snapshot TEXT NOT NULL DEFAULT '',
  caption TEXT NOT NULL DEFAULT '',
  storage_path TEXT NOT NULL UNIQUE,
  file_name TEXT NOT NULL DEFAULT '',
  mime_type TEXT NOT NULL DEFAULT 'image/jpeg',
  file_size BIGINT NOT NULL DEFAULT 0 CHECK (file_size >= 0),
  image_width INTEGER CHECK (image_width IS NULL OR image_width > 0),
  image_height INTEGER CHECK (image_height IS NULL OR image_height > 0),
  sort_order INTEGER NOT NULL DEFAULT 0,
  submitted_by UUID NOT NULL REFERENCES profiles(id) ON DELETE RESTRICT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_reading_media_assets_schedule
ON study_reading_media_assets(semester_id, schedule_instance_id, org_id, sort_order, id);

CREATE INDEX IF NOT EXISTS idx_reading_media_assets_demand
ON study_reading_media_assets(demand_id, assignment_person_id);

CREATE INDEX IF NOT EXISTS idx_reading_media_assets_submitted_by
ON study_reading_media_assets(submitted_by);

CREATE TABLE IF NOT EXISTS publicity_reading_posters (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  semester_id BIGINT NOT NULL REFERENCES semesters(id) ON DELETE CASCADE,
  schedule_instance_id BIGINT NOT NULL REFERENCES study_schedule_instances(id) ON DELETE CASCADE,
  org_id BIGINT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  title TEXT NOT NULL DEFAULT '',
  subtitle TEXT NOT NULL DEFAULT '',
  closing_text TEXT NOT NULL DEFAULT '在共读中照见彼此，在践行中抵达良知。',
  participant_count INTEGER CHECK (participant_count IS NULL OR participant_count >= 0),
  layout_style TEXT NOT NULL DEFAULT 'auto'
    CHECK (layout_style IN ('auto', 'compact', 'editorial', 'panorama')),
  status TEXT NOT NULL DEFAULT 'draft'
    CHECK (status IN ('draft', 'ready', 'published')),
  created_by UUID NOT NULL REFERENCES profiles(id) ON DELETE RESTRICT,
  updated_by UUID NOT NULL REFERENCES profiles(id) ON DELETE RESTRICT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (schedule_instance_id, org_id)
);

CREATE INDEX IF NOT EXISTS idx_publicity_reading_posters_scope
ON publicity_reading_posters(semester_id, org_id, schedule_instance_id, status);

CREATE TABLE IF NOT EXISTS publicity_reading_poster_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  poster_id BIGINT NOT NULL REFERENCES publicity_reading_posters(id) ON DELETE CASCADE,
  asset_id BIGINT NOT NULL REFERENCES study_reading_media_assets(id) ON DELETE CASCADE,
  slot_kind TEXT NOT NULL DEFAULT 'auto'
    CHECK (slot_kind IN ('auto', 'feature', 'role', 'overview', 'moment')),
  sort_order INTEGER NOT NULL DEFAULT 0,
  crop_x NUMERIC(6,3) NOT NULL DEFAULT 50 CHECK (crop_x BETWEEN 0 AND 100),
  crop_y NUMERIC(6,3) NOT NULL DEFAULT 50 CHECK (crop_y BETWEEN 0 AND 100),
  crop_zoom NUMERIC(5,3) NOT NULL DEFAULT 1 CHECK (crop_zoom BETWEEN 1 AND 4),
  rotation SMALLINT NOT NULL DEFAULT 0 CHECK (rotation IN (0, 90, 180, 270)),
  is_visible BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (poster_id, asset_id)
);

CREATE INDEX IF NOT EXISTS idx_publicity_reading_poster_items_order
ON publicity_reading_poster_items(poster_id, is_visible, sort_order, id);

CREATE OR REPLACE FUNCTION app_private.validate_reading_media_asset()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path = public
AS $$
DECLARE
  schedule_row study_schedule_instances%ROWTYPE;
  assigned_name TEXT;
  assigned_role TEXT;
BEGIN
  SELECT *
  INTO schedule_row
  FROM study_schedule_instances
  WHERE id = NEW.schedule_instance_id;

  IF NOT FOUND
     OR schedule_row.semester_id IS DISTINCT FROM NEW.semester_id
     OR schedule_row.org_id IS DISTINCT FROM NEW.org_id THEN
    RAISE EXCEPTION '共读影像必须关联同一学期和组织的日程';
  END IF;

  IF NEW.assignment_person_id IS NOT NULL THEN
    SELECT person.person_name_snapshot, demand.role_name
    INTO assigned_name, assigned_role
    FROM study_assignment_people person
    JOIN study_assignment_demands demand ON demand.id = person.demand_id
    WHERE person.id = NEW.assignment_person_id
      AND demand.schedule_instance_id = NEW.schedule_instance_id;

    IF assigned_name IS NULL THEN
      RAISE EXCEPTION '所选岗位人员不属于当前共读日程';
    END IF;

    NEW.demand_id = (
      SELECT demand_id
      FROM study_assignment_people
      WHERE id = NEW.assignment_person_id
    );
    NEW.person_name_snapshot = assigned_name;
    NEW.role_name_snapshot = COALESCE(assigned_role, '');
    NEW.asset_kind = 'role';
  ELSIF NEW.demand_id IS NOT NULL AND NOT EXISTS (
    SELECT 1
    FROM study_assignment_demands demand
    WHERE demand.id = NEW.demand_id
      AND demand.schedule_instance_id = NEW.schedule_instance_id
  ) THEN
    RAISE EXCEPTION '所选岗位不属于当前共读日程';
  END IF;

  NEW.caption = BTRIM(COALESCE(NEW.caption, ''));
  NEW.file_name = BTRIM(COALESCE(NEW.file_name, ''));
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_validate_reading_media_asset ON study_reading_media_assets;
CREATE TRIGGER trg_validate_reading_media_asset
BEFORE INSERT OR UPDATE ON study_reading_media_assets
FOR EACH ROW EXECUTE FUNCTION app_private.validate_reading_media_asset();

CREATE OR REPLACE FUNCTION app_private.validate_publicity_reading_poster()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path = public
AS $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM study_schedule_instances schedule
    WHERE schedule.id = NEW.schedule_instance_id
      AND schedule.semester_id = NEW.semester_id
      AND schedule.org_id = NEW.org_id
  ) THEN
    RAISE EXCEPTION '晨读长图必须关联同一学期和组织的日程';
  END IF;

  NEW.title = BTRIM(COALESCE(NEW.title, ''));
  NEW.subtitle = BTRIM(COALESCE(NEW.subtitle, ''));
  NEW.closing_text = BTRIM(COALESCE(NEW.closing_text, ''));
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_validate_publicity_reading_poster ON publicity_reading_posters;
CREATE TRIGGER trg_validate_publicity_reading_poster
BEFORE INSERT OR UPDATE ON publicity_reading_posters
FOR EACH ROW EXECUTE FUNCTION app_private.validate_publicity_reading_poster();

CREATE OR REPLACE FUNCTION app_private.validate_publicity_reading_poster_item()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path = public
AS $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM publicity_reading_posters poster
    JOIN study_reading_media_assets asset
      ON asset.id = NEW.asset_id
     AND asset.schedule_instance_id = poster.schedule_instance_id
     AND asset.org_id = poster.org_id
    WHERE poster.id = NEW.poster_id
  ) THEN
    RAISE EXCEPTION '所选照片不属于当前晨读长图';
  END IF;

  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_validate_publicity_reading_poster_item
ON publicity_reading_poster_items;
CREATE TRIGGER trg_validate_publicity_reading_poster_item
BEFORE INSERT OR UPDATE ON publicity_reading_poster_items
FOR EACH ROW EXECUTE FUNCTION app_private.validate_publicity_reading_poster_item();

ALTER TABLE study_reading_media_assets ENABLE ROW LEVEL SECURITY;
ALTER TABLE publicity_reading_posters ENABLE ROW LEVEL SECURITY;
ALTER TABLE publicity_reading_poster_items ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "学委和宣委可查看共读影像" ON study_reading_media_assets;
CREATE POLICY "学委和宣委可查看共读影像"
ON study_reading_media_assets FOR SELECT
TO authenticated
USING (
  app_private.has_module_org_scope(semester_id, 'study', org_id, NULL)
  OR app_private.has_module_org_scope(semester_id, 'publicity', org_id, NULL)
);

DROP POLICY IF EXISTS "学委可提交共读影像" ON study_reading_media_assets;
CREATE POLICY "学委可提交共读影像"
ON study_reading_media_assets FOR INSERT
TO authenticated
WITH CHECK (
  app_private.has_module_org_scope(semester_id, 'study', org_id, NULL)
  AND submitted_by = auth.uid()
);

DROP POLICY IF EXISTS "学委可修改共读影像" ON study_reading_media_assets;
CREATE POLICY "学委可修改共读影像"
ON study_reading_media_assets FOR UPDATE
TO authenticated
USING (
  app_private.has_module_org_scope(semester_id, 'study', org_id, NULL)
)
WITH CHECK (
  app_private.has_module_org_scope(semester_id, 'study', org_id, NULL)
  AND submitted_by = auth.uid()
);

DROP POLICY IF EXISTS "学委可删除共读影像" ON study_reading_media_assets;
CREATE POLICY "学委可删除共读影像"
ON study_reading_media_assets FOR DELETE
TO authenticated
USING (
  app_private.has_module_org_scope(semester_id, 'study', org_id, NULL)
);

DROP POLICY IF EXISTS "宣委可查看晨读长图" ON publicity_reading_posters;
CREATE POLICY "宣委可查看晨读长图"
ON publicity_reading_posters FOR SELECT
TO authenticated
USING (
  app_private.has_module_org_scope(semester_id, 'publicity', org_id, NULL)
);

DROP POLICY IF EXISTS "宣委可创建晨读长图" ON publicity_reading_posters;
CREATE POLICY "宣委可创建晨读长图"
ON publicity_reading_posters FOR INSERT
TO authenticated
WITH CHECK (
  app_private.has_module_org_scope(semester_id, 'publicity', org_id, NULL)
  AND created_by = auth.uid()
  AND updated_by = auth.uid()
);

DROP POLICY IF EXISTS "宣委可修改晨读长图" ON publicity_reading_posters;
CREATE POLICY "宣委可修改晨读长图"
ON publicity_reading_posters FOR UPDATE
TO authenticated
USING (
  app_private.has_module_org_scope(semester_id, 'publicity', org_id, NULL)
)
WITH CHECK (
  app_private.has_module_org_scope(semester_id, 'publicity', org_id, NULL)
  AND updated_by = auth.uid()
);

DROP POLICY IF EXISTS "宣委可删除晨读长图" ON publicity_reading_posters;
CREATE POLICY "宣委可删除晨读长图"
ON publicity_reading_posters FOR DELETE
TO authenticated
USING (
  app_private.has_module_org_scope(semester_id, 'publicity', org_id, NULL)
);

DROP POLICY IF EXISTS "宣委可查看晨读长图素材" ON publicity_reading_poster_items;
CREATE POLICY "宣委可查看晨读长图素材"
ON publicity_reading_poster_items FOR SELECT
TO authenticated
USING (
  EXISTS (
    SELECT 1
    FROM publicity_reading_posters poster
    WHERE poster.id = publicity_reading_poster_items.poster_id
      AND app_private.has_module_org_scope(
        poster.semester_id, 'publicity', poster.org_id, NULL
      )
  )
);

DROP POLICY IF EXISTS "宣委可管理晨读长图素材" ON publicity_reading_poster_items;
CREATE POLICY "宣委可管理晨读长图素材"
ON publicity_reading_poster_items FOR ALL
TO authenticated
USING (
  EXISTS (
    SELECT 1
    FROM publicity_reading_posters poster
    WHERE poster.id = publicity_reading_poster_items.poster_id
      AND app_private.has_module_org_scope(
        poster.semester_id, 'publicity', poster.org_id, NULL
      )
  )
)
WITH CHECK (
  EXISTS (
    SELECT 1
    FROM publicity_reading_posters poster
    WHERE poster.id = publicity_reading_poster_items.poster_id
      AND app_private.has_module_org_scope(
        poster.semester_id, 'publicity', poster.org_id, NULL
      )
  )
);

-- 宣委需要直接读取学委日程、共读类型、岗位和人员。
DROP POLICY IF EXISTS "宣委可查看共读日程" ON study_schedule_instances;
CREATE POLICY "宣委可查看共读日程"
ON study_schedule_instances FOR SELECT
TO authenticated
USING (
  app_private.has_module_org_scope(semester_id, 'publicity', org_id, NULL)
);

DROP POLICY IF EXISTS "宣委可查看共读类型" ON study_reading_types;
CREATE POLICY "宣委可查看共读类型"
ON study_reading_types FOR SELECT
TO authenticated
USING (
  app_private.has_module_org_scope(semester_id, 'publicity', org_id, NULL)
);

DROP POLICY IF EXISTS "宣委可查看共读类型岗位" ON study_reading_type_positions;
CREATE POLICY "宣委可查看共读类型岗位"
ON study_reading_type_positions FOR SELECT
TO authenticated
USING (
  EXISTS (
    SELECT 1
    FROM study_reading_types reading_type
    WHERE reading_type.id = study_reading_type_positions.reading_type_id
      AND app_private.has_module_org_scope(
        reading_type.semester_id, 'publicity', reading_type.org_id, NULL
      )
  )
);

DROP POLICY IF EXISTS "宣委可查看共读岗位安排" ON study_assignment_demands;
CREATE POLICY "宣委可查看共读岗位安排"
ON study_assignment_demands FOR SELECT
TO authenticated
USING (
  EXISTS (
    SELECT 1
    FROM study_schedule_instances schedule
    WHERE schedule.id = study_assignment_demands.schedule_instance_id
      AND app_private.has_module_org_scope(
        schedule.semester_id, 'publicity', schedule.org_id, NULL
      )
  )
);

DROP POLICY IF EXISTS "宣委可查看共读岗位人员" ON study_assignment_people;
CREATE POLICY "宣委可查看共读岗位人员"
ON study_assignment_people FOR SELECT
TO authenticated
USING (
  EXISTS (
    SELECT 1
    FROM study_assignment_demands demand
    JOIN study_schedule_instances schedule
      ON schedule.id = demand.schedule_instance_id
    WHERE demand.id = study_assignment_people.demand_id
      AND app_private.has_module_org_scope(
        schedule.semester_id, 'publicity', schedule.org_id, NULL
      )
  )
);

DROP POLICY IF EXISTS "宣委可查看共读内容" ON study_schedule_content;
CREATE POLICY "宣委可查看共读内容"
ON study_schedule_content FOR SELECT
TO authenticated
USING (
  EXISTS (
    SELECT 1
    FROM study_schedule_instances schedule
    WHERE schedule.id = study_schedule_content.schedule_instance_id
      AND app_private.has_module_org_scope(
        schedule.semester_id, 'publicity', schedule.org_id, NULL
      )
  )
);

GRANT SELECT, INSERT, UPDATE, DELETE ON study_reading_media_assets
TO authenticated, service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON publicity_reading_posters
TO authenticated, service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON publicity_reading_poster_items
TO authenticated, service_role;
GRANT USAGE, SELECT ON SEQUENCE study_reading_media_assets_id_seq
TO authenticated, service_role;
GRANT USAGE, SELECT ON SEQUENCE publicity_reading_posters_id_seq
TO authenticated, service_role;
GRANT USAGE, SELECT ON SEQUENCE publicity_reading_poster_items_id_seq
TO authenticated, service_role;

-- 原图保存在私有桶，路径固定为：学期/组织/日程/文件。
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'reading-media',
  'reading-media',
  FALSE,
  15728640,
  ARRAY['image/jpeg', 'image/png', 'image/webp']
)
ON CONFLICT (id) DO UPDATE
SET
  public = EXCLUDED.public,
  file_size_limit = EXCLUDED.file_size_limit,
  allowed_mime_types = EXCLUDED.allowed_mime_types;

CREATE OR REPLACE FUNCTION app_private.can_access_reading_media_object(
  object_name TEXT,
  target_module_key TEXT
)
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, storage
AS $$
  WITH path_parts AS (
    SELECT storage.foldername(object_name) AS parts
  )
  SELECT
    auth.uid() IS NOT NULL
    AND COALESCE(array_length(parts, 1), 0) >= 2
    AND parts[1] ~ '^[0-9]+$'
    AND parts[2] ~ '^[0-9]+$'
    AND app_private.has_module_org_scope(
      parts[1]::BIGINT,
      target_module_key,
      parts[2]::BIGINT,
      NULL
    )
  FROM path_parts;
$$;

REVOKE ALL ON FUNCTION app_private.can_access_reading_media_object(TEXT, TEXT)
FROM PUBLIC;
GRANT EXECUTE ON FUNCTION app_private.can_access_reading_media_object(TEXT, TEXT)
TO authenticated;

DROP POLICY IF EXISTS "学委和宣委可读取共读影像文件" ON storage.objects;
CREATE POLICY "学委和宣委可读取共读影像文件"
ON storage.objects FOR SELECT
TO authenticated
USING (
  bucket_id = 'reading-media'
  AND (
    app_private.can_access_reading_media_object(name, 'study')
    OR app_private.can_access_reading_media_object(name, 'publicity')
  )
);

DROP POLICY IF EXISTS "学委可上传共读影像文件" ON storage.objects;
CREATE POLICY "学委可上传共读影像文件"
ON storage.objects FOR INSERT
TO authenticated
WITH CHECK (
  bucket_id = 'reading-media'
  AND app_private.can_access_reading_media_object(name, 'study')
);

DROP POLICY IF EXISTS "学委可更新共读影像文件" ON storage.objects;
CREATE POLICY "学委可更新共读影像文件"
ON storage.objects FOR UPDATE
TO authenticated
USING (
  bucket_id = 'reading-media'
  AND app_private.can_access_reading_media_object(name, 'study')
)
WITH CHECK (
  bucket_id = 'reading-media'
  AND app_private.can_access_reading_media_object(name, 'study')
);

DROP POLICY IF EXISTS "学委可删除共读影像文件" ON storage.objects;
CREATE POLICY "学委可删除共读影像文件"
ON storage.objects FOR DELETE
TO authenticated
USING (
  bucket_id = 'reading-media'
  AND app_private.can_access_reading_media_object(name, 'study')
);
