-- ============================================================
-- 学委工作流 v3：多课程、共读类型岗位模板
-- ============================================================

-- 1. 一个组织日程可配置多条课程内容。
ALTER TABLE study_schedule_content
  ADD COLUMN IF NOT EXISTS sort_order INTEGER NOT NULL DEFAULT 10;

DROP INDEX IF EXISTS idx_study_schedule_content_unique;

CREATE UNIQUE INDEX IF NOT EXISTS idx_study_schedule_content_order_unique
ON study_schedule_content(schedule_instance_id, org_id, sort_order);

CREATE INDEX IF NOT EXISTS idx_study_schedule_content_schedule_order
ON study_schedule_content(schedule_instance_id, org_id, sort_order, id);

-- 2. 每个大班的每种共读类型独立维护岗位、标准人数和启停状态。
CREATE TABLE IF NOT EXISTS study_reading_type_roles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  semester_id BIGINT NOT NULL REFERENCES semesters(id) ON DELETE CASCADE,
  org_id BIGINT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  scope_level TEXT NOT NULL CHECK (scope_level IN ('大班', '班级', '小组')),
  role_id BIGINT NOT NULL REFERENCES study_roles(id) ON DELETE CASCADE,
  required_count INTEGER NOT NULL DEFAULT 1 CHECK (required_count > 0),
  is_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_by UUID REFERENCES profiles(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (semester_id, org_id, scope_level, role_id)
);

CREATE INDEX IF NOT EXISTS idx_study_reading_type_roles_lookup
ON study_reading_type_roles(semester_id, org_id, scope_level, is_enabled, sort_order, id);

-- 已有大班岗位自动成为三种共读类型的初始模板，默认每岗 1 人。
INSERT INTO study_reading_type_roles (
  semester_id,
  org_id,
  scope_level,
  role_id,
  required_count,
  is_enabled,
  sort_order
)
SELECT
  r.semester_id,
  r.org_id,
  scope.scope_level,
  r.id,
  1,
  r.is_active,
  r.sort_order
FROM study_roles r
CROSS JOIN (VALUES ('大班'), ('班级'), ('小组')) AS scope(scope_level)
ON CONFLICT (semester_id, org_id, scope_level, role_id) DO NOTHING;

ALTER TABLE study_reading_type_roles ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "学委可查看共读类型岗位" ON study_reading_type_roles;
CREATE POLICY "学委可查看共读类型岗位" ON study_reading_type_roles FOR SELECT
  TO authenticated
  USING (
    app_private.has_module_access(
      semester_id,
      'study',
      ARRAY['学委', '副学委', '管理员', 'admin', 'manager']
    )
  );

DROP POLICY IF EXISTS "大班学委可管理共读类型岗位" ON study_reading_type_roles;
CREATE POLICY "大班学委可管理共读类型岗位" ON study_reading_type_roles FOR ALL
  TO authenticated
  USING (
    app_private.has_study_membership_at_org(
      semester_id,
      org_id,
      ARRAY['学委', '副学委', '管理员', 'admin', 'manager']
    )
  )
  WITH CHECK (
    app_private.has_study_membership_at_org(
      semester_id,
      org_id,
      ARRAY['学委', '副学委', '管理员', 'admin', 'manager']
    )
  );

GRANT SELECT, INSERT, UPDATE, DELETE ON study_reading_type_roles TO authenticated, service_role;
GRANT USAGE, SELECT ON SEQUENCE study_reading_type_roles_id_seq TO authenticated, service_role;
