-- ============================================================
-- 学委工作流 v2：按大班规则、组织节点日程、内容继承、岗位表
-- Execute after 20260620090624_20260620000001_harden_permissions_rls.sql.
-- ============================================================

-- 1. 日程规则从“全学期一套”升级为“每个大班一套”
ALTER TABLE study_schedule_rules
  ADD COLUMN IF NOT EXISTS org_id BIGINT REFERENCES organizations(id) ON DELETE CASCADE,
  ADD COLUMN IF NOT EXISTS created_by UUID REFERENCES profiles(id) ON DELETE SET NULL;

DROP INDEX IF EXISTS idx_study_schedule_rules_unique;

CREATE UNIQUE INDEX IF NOT EXISTS idx_study_schedule_rules_org_unique
ON study_schedule_rules(semester_id, org_id, weekday);

CREATE INDEX IF NOT EXISTS idx_study_schedule_rules_semester_org
ON study_schedule_rules(semester_id, org_id, is_active);

-- 2. 岗位表：各大班维护可调用岗位
CREATE TABLE IF NOT EXISTS study_roles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  semester_id BIGINT NOT NULL REFERENCES semesters(id) ON DELETE CASCADE,
  org_id BIGINT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  role_name TEXT NOT NULL,
  role_type TEXT NOT NULL DEFAULT '通用' CHECK (role_type IN ('通用', '承办', '参与')),
  sort_order INTEGER NOT NULL DEFAULT 0,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_by UUID REFERENCES profiles(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_study_roles_unique
ON study_roles(semester_id, org_id, role_name);

CREATE INDEX IF NOT EXISTS idx_study_roles_active
ON study_roles(semester_id, org_id, is_active, sort_order, id);

-- 3. 日程内容覆盖表：保留实例表旧 custom 字段，新工作台优先读本表
CREATE TABLE IF NOT EXISTS study_schedule_content (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  schedule_instance_id BIGINT NOT NULL REFERENCES study_schedule_instances(id) ON DELETE CASCADE,
  org_id BIGINT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  course_id BIGINT REFERENCES study_course_library(id) ON DELETE SET NULL,
  custom_title TEXT,
  custom_theme TEXT,
  custom_content TEXT,
  custom_question TEXT,
  custom_paper_pages TEXT,
  custom_ebook_url TEXT,
  is_template BOOLEAN NOT NULL DEFAULT FALSE,
  note TEXT,
  created_by UUID REFERENCES profiles(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_study_schedule_content_unique
ON study_schedule_content(schedule_instance_id, org_id);

CREATE INDEX IF NOT EXISTS idx_study_schedule_content_org
ON study_schedule_content(org_id, schedule_instance_id);

-- 4. 摊派与落位增强：支持逐级摊派、岗位表引用、最终小组归属
ALTER TABLE study_assignment_demands
  ADD COLUMN IF NOT EXISTS parent_demand_id BIGINT REFERENCES study_assignment_demands(id) ON DELETE CASCADE,
  ADD COLUMN IF NOT EXISTS role_id BIGINT REFERENCES study_roles(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'assigned', 'completed', 'cancelled'));

ALTER TABLE study_assignment_people
  ADD COLUMN IF NOT EXISTS org_id BIGINT REFERENCES organizations(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_study_demands_parent
ON study_assignment_demands(parent_demand_id);

CREATE INDEX IF NOT EXISTS idx_study_demands_role
ON study_assignment_demands(role_id);

CREATE INDEX IF NOT EXISTS idx_study_people_org
ON study_assignment_people(org_id);

-- 5. 默认岗位种子：每个大班给一套常用岗位，可在前端继续维护
INSERT INTO study_roles (semester_id, org_id, role_name, role_type, sort_order)
SELECT o.semester_id, o.id, seed.role_name, seed.role_type, seed.sort_order
FROM organizations o
CROSS JOIN (
  VALUES
    ('主持人', '通用', 10),
    ('聆听者', '参与', 20),
    ('分享人', '参与', 30),
    ('回应砥砺', '参与', 40),
    ('总结赋能', '承办', 50),
    ('播控', '承办', 60),
    ('拍照', '承办', 70)
) AS seed(role_name, role_type, sort_order)
WHERE o.level = '大班'
ON CONFLICT (semester_id, org_id, role_name) DO NOTHING;

-- 6. RLS 与 Data API 显式授权
CREATE OR REPLACE FUNCTION app_private.has_study_membership_at_org(
  target_semester_id BIGINT,
  target_org_id BIGINT,
  allowed_roles TEXT[] DEFAULT ARRAY['学委', '副学委', '管理员', 'admin', 'manager']
)
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT app_private.is_platform_admin()
    OR EXISTS (
      SELECT 1
      FROM module_memberships m
      WHERE m.user_id = auth.uid()
        AND m.semester_id = target_semester_id
        AND m.module_key = 'study'
        AND m.enabled = TRUE
        AND (allowed_roles IS NULL OR m.role = ANY(allowed_roles))
        AND (
          m.org_id = target_org_id
          OR (m.org_id IS NULL AND m.role IN ('管理员', 'admin', 'manager'))
        )
    );
$$;

REVOKE ALL ON FUNCTION app_private.has_study_membership_at_org(BIGINT, BIGINT, TEXT[]) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION app_private.has_study_membership_at_org(BIGINT, BIGINT, TEXT[]) TO authenticated;

ALTER TABLE study_roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE study_schedule_content ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "学委可管理日程规则" ON study_schedule_rules;
DROP POLICY IF EXISTS "大班学委可管理本大班日程规则" ON study_schedule_rules;
CREATE POLICY "大班学委可管理本大班日程规则" ON study_schedule_rules FOR ALL
  TO authenticated
  USING (app_private.has_study_membership_at_org(semester_id, org_id, ARRAY['学委', '副学委', '管理员', 'admin', 'manager']))
  WITH CHECK (app_private.has_study_membership_at_org(semester_id, org_id, ARRAY['学委', '副学委', '管理员', 'admin', 'manager']));

DROP POLICY IF EXISTS "学委可管理岗位" ON study_roles;
DROP POLICY IF EXISTS "学委可查看岗位" ON study_roles;
CREATE POLICY "学委可查看岗位" ON study_roles FOR SELECT
  TO authenticated
  USING (app_private.has_module_access(semester_id, 'study', ARRAY['学委', '副学委', '管理员', 'admin', 'manager']));

CREATE POLICY "学委可管理岗位" ON study_roles FOR ALL
  TO authenticated
  USING (app_private.has_study_membership_at_org(semester_id, org_id, ARRAY['学委', '副学委', '管理员', 'admin', 'manager']))
  WITH CHECK (app_private.has_study_membership_at_org(semester_id, org_id, ARRAY['学委', '副学委', '管理员', 'admin', 'manager']));

DROP POLICY IF EXISTS "学委可管理日程内容" ON study_schedule_content;
DROP POLICY IF EXISTS "学委可查看日程内容" ON study_schedule_content;
CREATE POLICY "学委可查看日程内容" ON study_schedule_content FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1
      FROM study_schedule_instances si
      WHERE si.id = study_schedule_content.schedule_instance_id
        AND app_private.has_module_access(si.semester_id, 'study', ARRAY['学委', '副学委', '管理员', 'admin', 'manager'])
    )
  );

CREATE POLICY "学委可管理日程内容" ON study_schedule_content FOR ALL
  TO authenticated
  USING (
    EXISTS (
      SELECT 1
      FROM study_schedule_instances si
      WHERE si.id = study_schedule_content.schedule_instance_id
        AND app_private.has_study_membership_at_org(si.semester_id, study_schedule_content.org_id, ARRAY['学委', '副学委', '管理员', 'admin', 'manager'])
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1
      FROM study_schedule_instances si
      WHERE si.id = study_schedule_content.schedule_instance_id
        AND app_private.has_study_membership_at_org(si.semester_id, study_schedule_content.org_id, ARRAY['学委', '副学委', '管理员', 'admin', 'manager'])
    )
  );

GRANT SELECT, INSERT, UPDATE, DELETE ON study_roles TO authenticated, service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON study_schedule_content TO authenticated, service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON study_schedule_rules TO authenticated, service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON study_schedule_instances TO authenticated, service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON study_assignment_demands TO authenticated, service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON study_assignment_people TO authenticated, service_role;
GRANT USAGE, SELECT ON SEQUENCE study_roles_id_seq TO authenticated, service_role;
GRANT USAGE, SELECT ON SEQUENCE study_schedule_content_id_seq TO authenticated, service_role;
